Traceback (most recent call last):
  File "./geolocate.py", line 104, in <module>
    actual_loc, tweet = line.split(' ', 1)
ValueError: need more than 1 value to unpack
